services:
  sikeu-core-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: sikeu-core-dev
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - sikeu_dev_network
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

networks:
  sikeu_dev_network:
    driver: bridge
    internal: true
