FROM node:22.14.0-alpine

# Install necessary packages
RUN apk update && apk add --no-cache yarn tzdata
ENV TZ=Asia/Jakarta
RUN cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo "Asia/Jakarta" > /etc/timezone

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package.json .

# Copy source code
COPY . .

# Copy .env.example to .env
RUN cp .env.example .env

# Install dependencies locally and globally, and clean yarn cache
RUN yarn install
RUN yarn global add ts-node nodemon
ENV PATH=$PATH:/usr/src/app/node_modules/.bin
RUN yarn cache clean --all

# Start the application
# CMD ["yarn", "start:dev"]
CMD ["node_modules/.bin/nodemon", "--watch", "src/**", "--ext", "ts,json", "--ignore", "src/**/*.spec.ts", "--exec", "node_modules/.bin/ts-node", "src/server.ts"]

