services:
  finance_core_app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    container_name: finance_core_app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - finance_mysql
      - finance_rabbitmq
      - finance_redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: on-failure
    env_file:
      - .env
    networks:
      - finance_core_network
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

  finance_mysql:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.mysql.windows
    container_name: finance_mysql
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - '3307:${DB_PORT}'
    volumes:
      - finance_mysql_data:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d/
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - finance_core_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  finance_rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: finance_rabbitmq
    restart: always
    ports:
      - '5677:${RABBITMQ_PORT}'
      - '15677:15672'
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - finance_core_network

  finance_redis:
    image: redis:latest
    container_name: finance_redis
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASS}']
    networks:
      - finance_core_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  finance_mysql_data:
    name: finance_mysql_data
    driver: local

networks:
  finance_core_network:
    name: finance_core_network
    driver: bridge
