USE mysql;
CREATE USER 'admin'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE db_financial;
GRANT ALL PRIVILEGES ON db_financial.* TO 'admin'@'%';
FLUSH PRIVILEGES;