USE mysql;
CREATE USER 'admin'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE sikeu_unimed;
GRANT ALL PRIVILEGES ON sikeu_unimed.* TO 'admin'@'%';
FLUSH PRIVILEGES;